### PR TITLE
Make dmsort work with non-default-constructible types (fixes #1)

### LINKED ISSUE #1: Drop-merge sort does not work with types that are not default-constructible
I've got a [small helper type](https://github.com/Morwenn/cpp-sort/blob/master/testsuite/move_only.h) in a sorting library of mine to check that a sorting algorithm supports the same requirements as `std::sort`:
* It works with move-only types
* It works with types that are not default-constructible
* It even checks that it does not perform any read from a moved-from object

While your drop-merge sort does work with move-only types, it seems that it doesn't like types that are not default-constructible. When I tried to use the aforementioned type, it chocked on `std::vector::resize`. Apparently, dropping the `resize` and using a loop of equivalent `pop_back` in its stead is enough to make the algorithm work with types that are not default-constructible.

### PR DESCRIPTION
**Pull request by Morwenn**
See issue #1 for the detail.

### CODE REVIEW

**Comment by adrian17** [comment]
Nice find, and silly `resize`. Thanks.

I'll repeat the benchmarks with this change later (in ~12h) (although it's far from the critical part of the algorithm, so it shouldn't matter anyway) and most likely merge it then.

File: drop_merge_sort.hpp [hunk 1]
```diff
@@ -126,12 +126,13 @@ namespace detail {
                     ++read;
                     ++num_dropped_in_row;
                 } else {
-                    size_t trunc_to_length = dropped.size() - num_dropped_in_row;
                     for (int i = 0; i < num_dropped_in_row; ++i) {
                         --read;
                         *read = std::move(*(dropped.end() - (i+1)));
                     }
-                    dropped.resize(trunc_to_length);
+                    for (int i = 0; i < num_dropped_in_row; ++i) {
```
Comment (adrian17) [inline drop_merge_sort.hpp]: This can most likely be merged with the loop above:

                    for (int i = 0; i < num_dropped_in_row; ++i) {
                        --read;
                        *read = std::move(*(dropped.end() - 1));
                        dropped.pop_back();
                    }

**Review by adrian17 — CHANGES_REQUESTED** [review]
Hm, the second overload (with-trivial-copies) may also need this, because a type may be trivially copyable and not be default constructible.

File: drop_merge_sort.hpp (hunk 1 above)
Comment (Morwenn) [reply drop_merge_sort.hpp]: Sure, we could try that too, that might be more sensible.

**Comment by Morwenn** [comment]
Eh, it's true that I didn't think of trivially copyable types that are not default-constructible, but I guess that such types can indeed exist. Good catch.

**Comment by Morwenn** [comment]
By the way, it looks like the algorithm could easily be made to work with bidirectional iterators instead of random-access ones. The changes I see to make the magic happen:
* Replace `read -= num_dropped_in_row;` by `std::advance(read, -num_dropped_in_row)`, first chaging `num_dropped_in_row` to a signed type (`std::iterator_traits<Iter>::difference_type` looks like a good choice for that)
* Replace a few `it - 1` by `std::prev(it)` and `it + 1` by `std::next(it)`

Apparently, the algorithm almost never performs big jumps in the collection, so making it work with bidirectional iterators could be worth (unlike *e.g.* heapsort). You may want to consider it since there aren't many good sorting algorithms for bidirectional iterators :)

---

My small tests on one million integer lists show that it's more than decent for bidirectional iterators too (ok, the more efficient would still probably be to move everything to a vector, sort it, and move everything back):

look at me

**Comment by adrian17** [comment]
Thank you.

I'll take a look at bidirectional iterator changes too, thanks for that advice too!
